astrosat/django-astrosat-users

astrosat_users/__init__.py, astrosat_users/serializers.py, example/Pipfile.lock, example/example/models.py, example/example/tests/conftest.py
Roles are no longer serialized in their entirety on a user.  And they are no longer writable w/in the user API.  Instead a list of role names and a separate list of (unique) permission names are serialized.
This PR also fixed #9.
And  a bit of linting ocurred.
IssueID #12
=> Changed how Roles & Permissions are serialized for a User.

astrosat_users/admin/admin_users.py, astrosat_users/models/models_users.py, astrosat_users/serializers/serializers_auth.py, astrosat_users/serializers/serializers_users.py, astrosat_users/tests/factories.py, astrosat_users/views/views_api_users.py, example/Pipfile, example/Pipfile.lock, example/example/settings.py, example/example/tests/factories.py, example/example/tests/test_user_views.py
Added some filters for the User API:
- `is_active`
- `is_approved`
- `is_verified`
- `roles__any`
- `roles__all`
- `permissions__any`
- `permissions__all`
Added `toggle_approval` & `toggle_verification` actions to the User Admin.
Did some linting.
Closes #29
=> Added some filters for the User API

astrosat_users/models/models_roles.py
=> feat(backend): alter str method of UserRole

astrosat_users/admin/admin_customers.py, astrosat_users/models/models_customers.py, astrosat_users/serializers/serializers_customers.py, astrosat_users/tests/factories.py, astrosat_users/views/views_customers.py
* removed UserRoles from Customers
* removed ContextVariableDefault class (moved to django-astrosat-core)
* cleaned up bits of old code
=> chore(backend): preparatory work for licenses

astrosat_users/models/models_customers.py, astrosat_users/serializers/serializers_customers.py, astrosat_users/views/views_customers.py
Just making sure `invitation_date` gets set when adding a `CustomerUser`.
=> feat(backend): initial support for invitations

astrosat_users/serializers/serializers_users.py
Added `is_verified`, `is_approved`, and `accepted_terms` to the `UserSerializerLite` class which is used for login errors.  It exposes
some user information to the client, but nothing sensitive.
IssueID #82
=> feat(backend): extended login failure response

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/test.yml
This PR closes #97 and closes #98 
I've updated Issue Templates, based on existing but more stripped down to really all we need. These include templates for:
Bug
Feature
Pull Requests
I have also added a workflow to manage the setup and running of tests on push. This will run for PRs and when merged into master.
=> 97 GitHub workflow

astrosat_users/adapters.py, astrosat_users/models/models_customers.py, astrosat_users/templates/astrosat_users/email/uninvitation_subject.txt
Added the ability to cc recipients when sending email via the adapter.
This PR closes #109
=> feat(backend): added the ability to cc recipients

astrosat_users/templates/astrosat_users/email/admin_assign_message.txt, astrosat_users/templates/astrosat_users/email/admin_assign_subject.txt, astrosat_users/templates/astrosat_users/email/admin_revoke_message.txt, astrosat_users/templates/astrosat_users/email/admin_revoke_subject.txt, astrosat_users/templates/astrosat_users/email/update_customer_message.txt, astrosat_users/templates/astrosat_users/email/update_customer_subject.txt, astrosat_users/templates/astrosat_users/email/update_user_message.txt, astrosat_users/templates/astrosat_users/email/update_user_subject.txt, astrosat_users/views/views_customers.py, example/example/tests/test_customer_views.py
This PR closes #115 
Added notifications for the following situation:
* a user is granted/revoked MANAGER rights on a customer via API
* a user's details are changed from w/in the context of a customer (ie: by a customer manager in the admin panel) via API
* a customer's details are changed via API
=> 115 emails

astrosat_users/serializers/serializers_auth.py, astrosat_users/views/views_auth.py, example/example/tests/test_login_logout.py
Added an optional `accepted_terms` field to the LoginView.
=> feat(backend): added accepted_terms to login

astrosat_users/models/models_customers.py, astrosat_users/models/models_users.py, astrosat_users/views/views_customers.py, example/example/tests/test_customer_views.py
No longer automaticaly cc'ing any notification emails
=> feat(backend): do not cc emails

astrosat_users/serializers/serializers_customers.py
Gets around the problem of requiring `accepted_terms` to be True in order for registration to work, but needing it to be False in order to require `users` created via an invitation to a `customer` to explicitly accept_terms when logging in.  
Did this by setting it to True when _validating_ the `RegistrationSerializer` and then immediately setting it to False before _saving_ the `RegistrationSerializer`.
=> feat(backend): force accepted_terms to be false for new CustomerUsers

astrosat_users/admin/admin_customers.py
added `customer.created` to the admin
=> feat(backend): added customer.created to the admin

astrosat_users/tests/factories.py, example/Pipfile, example/Pipfile.lock
This involved upgrading the dependency to django-astrosat-core which refactored optional_dependency. Also had to replace various calls to FactoryBoy's wrapper of Faker w/ the actual Faker class itself.
=> feat(backend): unpin factory-boy

astrosat_users/models/models_users.py, astrosat_users/serializers/serializers_customers.py, example/Pipfile.lock
Upgraded dependencies as per dependabot-reported security vulnerabilities.
Also some linting.
=> chore(backend): upgraded dependencies

.vscode/settings.json, astrosat_users/adapters.py, astrosat_users/admin/admin_messages.py, astrosat_users/admin/admin_users.py, astrosat_users/conf/settings.py, astrosat_users/fields.py, astrosat_users/forms/forms_admin.py, astrosat_users/forms/forms_auth.py, astrosat_users/models/models_settings.py, astrosat_users/serializers/serializers_customers.py, astrosat_users/serializers/serializers_users.py, astrosat_users/views/views_auth.py, astrosat_users/views/views_customers.py, astrosat_users/views/views_messages.py, astrosat_users/views/views_users.py, example/example/tests/test_auth_api_errors.py, example/example/tests/test_customer_views.py, example/example/tests/test_login_logout.py, example/example/tests/test_messages.py, example/example/tests/test_user_serializers.py, example/example/tests/test_user_views.py, setup.py
Added new rules in the first commit, so the library now matches the formatting rules used in `django-astrosat-core`, for consistency.
I also re-formatted all files in the 2nd commit, so we don't get a mixture of actual changes and re-formatting changes in future PRs.
I suggest just reviewing the first commit and maybe checkout the branch and try to save one or two of the updated files, just to ensure all developers format the code the same.
=> Format python

astrosat_users/serializers/serializers_users.py, example/example/tests/test_user_serializers.py
Updated swagger documentation for `UserViewSet`
=> chore(backend): updated swagger documentation

astrosat_users/views/views_customers.py, example/example/tests/test_customer_views.py
Refactored customers permissions to allow some actions to be performed by managers _or_ members.  Also removed the special case that allowed all actions to be performed by site admins.
=> feat(backend): refactored customers permissions

example/Pipfile.lock
Updated this library to upgrade the version of the django-astrosat-core library.
=> Update to use the late django-astrosat-core library

astrosat_users/adapters.py, example/example/tests/test_auth_api_errors.py, example/example/tests/test_login_logout.py
=> chore(backend): update error message for unaccepted T&C

astrosat_users/admin/admin_roles.py, astrosat_users/admin/admin_users.py, example/Pipfile.lock
Updated the user admin to use a pretty widget for updating groups/permissions on a user.  And exposed the built-in Django
groups/permissions models in the admin.  Also updated dependencies.
=> feature(backend): updated the user admin

example/Pipfile.lock
Updated dependencies as per dependabot - crucially, django & pyjwt
=> feat(backend): updated dependencies
