astrosat_users/adapters.py, astrosat_users/admin/admin_users.py, astrosat_users/serializers/__init__.py, astrosat_users/serializers/serializers_auth.py, astrosat_users/urls.py, astrosat_users/views/__init__.py, astrosat_users/views/views_api_auth.py, example/example/tests/test_registration.py
After registration, the code tried to log a user in.  An unverified user
would not be able to login.  It would automatically send a new
verification email in that situation.  But, it would have just sent a
verification email as part of the registration process.
To address this, I stopped automatically sending a new verification
email during login.  And I added a new endpoint for sending a new
verification email.  In order for that to work, you need to pass it a
valid email address.  So, the error responses for unverified (and
unapproved) users now includes some minimal information about the user.
I also added a verify action to the user admin.
IssueID #27
=> bug(backend): prevent duplicate emails

astrosat_users/checks.py, astrosat_users/urls.py, astrosat_users/views/__init__.py, astrosat_users/views/views_tokens.py
Now that the API uses `TokenAuthentication`, a token must be passed w/ most requests.   
However, the backend still use `SessionAuthentication` for the standard Django workflow.  
I have therefore added an API endpoint for those clients where login/registration is done via the backend (ie: Django forms/templates) which generates a token to use for pure API calls.
=> added a generate-token endpoint

astrosat_users/forms/forms_admin.py, astrosat_users/forms/forms_auth.py, astrosat_users/models/models_roles.py, astrosat_users/models/models_settings.py, astrosat_users/models/models_users.py, astrosat_users/views/views_api_auth.py, example/Pipfile, example/Pipfile.lock, example/example/models.py, example/example/settings.py, setup.py
Upgraded dependencies.  Critically this included Django 3.x.  Note that
pytest-sugar has a conflict w/ a recent version of pytest.  For the
moment I have pinned pytest, but I plan to upgrade it soon.
=> feat(backend): upgraded dependencies

astrosat_users/models/models_profiles.py, astrosat_users/serializers/serializers_users.py, example/example/models.py, example/example/serializers.py
Added a `serializer_class` kwarg for `UserProfileField` that takes the name of a custom serializer to use.  The corresponding `UserProfile` is given a `get_serializer_class` fn that returns either that serializer or else the `GenericProfileSerializer` to use in serialization/deserialization.
IssueID #14
=> feat(backend): support for custom profile serializers

astrosat_users/views/views_customers.py
Some of the built-in DRF View methods that get called by Swagger when
generating API documentation require kwargs; these are obviously missing
during schema generation.  This fix protects those methods by returning
dummy values when the in "swagger-mode".
=> chore(backend): fixed swagger API generation

astrosat_users/adapters.py, astrosat_users/models/models_customers.py, astrosat_users/serializers/serializers_auth.py, astrosat_users/serializers/serializers_customers.py, astrosat_users/templates/astrosat_users/email/customer_user_password_reset_key_message.txt, astrosat_users/templates/astrosat_users/email/customer_user_password_reset_key_subject.txt, example/example/tests/test_customer_views.py
* when a new CustomerUser is created, do not automatically send them an email asking them to verify their email address - instead, send them an email asking them to reset their password
* added custom templates for the above email (rather than the built-in reset password template used in other situations)
* ensured a user cannot be added multiple times to the same customer
* when a CustomerUser resets their password, set them to "ACTIVE" and verify their email address (if it hasn't already been verified)
=> Customer user notifications

astrosat_users/templates/astrosat_users/email/message_base.txt, astrosat_users/templates/astrosat_users/email/user_left_customer_message.txt, astrosat_users/templates/astrosat_users/email/user_left_customer_subject.txt, astrosat_users/views/views_customers.py, example/example/tests/test_customer_views.py
Added some extra code to the `destroy` method of the CustomerUserDetailView to send a notification email to the corresponding user.  Added some silly templates for that email content; The templates are silly b/c I expect to overwrite them when used for a _real_ application.  Added a Permissions class to prevent a user from deleting themselves from a customer.  And added some tests for all of this.
=> feat(backend): send a notification when a user leaves a customer

astrosat_users/adapters.py
Overrode the default `AccountAdapter.populate_username` fn to simply use the email address as a username if the request doesn't already contain an explicit username.
Closes #65
=> feat(backend): added populate_username fn

astrosat_users/validators.py, example/example/settings.py
Refactored password validators to use dynamic settings by default;
otherwise I would have to reference astrosat_users dynamic settings in
the project settings which could potentially cause circular dependency
issues.  Now I only need to add options to the password validators if I
_don't_ want to use the default dynamic settings.
=> feat(backend): refactored password validators 

astrosat_users/adapters.py
This PR closes #74
This worked perfectly fine while the server, served the client, now they are separate, I have had to update how we construct the URL.
=> Ensure URL in emails is to the CLIENT, not SERVER

astrosat_users/adapters.py, astrosat_users/tests/utils.py
Updated `generate_password` utility function to no longer call **factoryboy's** faker wrapper `generate` fn b/c that is intended to be _private_ method.  Instead, using **faker** itself.
Also updated the recent changes to `get_password_confirmation_email` and `get_email_confirmation_email` to not _always_ assume that the client/server are on different domains.
=> feat(backend): dont wrap faker

astrosat_users/tests/factories.py, astrosat_users/urls.py, astrosat_users/views/__init__.py, astrosat_users/views/views_customers.py, example/example/tests/test_customer_views.py
Added a new view class to create `customers`.
Closes #83
=> feat(backend): make customer createable via API

astrosat_users/adapters.py, astrosat_users/serializers/serializers_auth.py, astrosat_users/views/views_auth.py, example/example/tests/test_registration.py
Return some user information (from `UserSerializerLite`) as part of the `VerifyEmailView` response.  This will allow the frontend to determine where to redirect after a successful user account activation.
Closes #92
=> feat(backend): return some user information from VerifyEmailView

astrosat_users/serializers/serializers_auth.py, astrosat_users/serializers/serializers_users.py, astrosat_users/views/views_auth.py
Prevent "stringification" of nested JSON in invalid login responses by no longer adding `UserSerializerLite` content into the `ValidationError` message automatically returned by the `LoginSerializer`.  Instead, instead manually create an error response in the `LoginView` which may or may not include `UserSerializerLite` content depending on how far validation got in the `LoginSerializer`.
Closes #100
=> fix(backend): return correct data for invalid logins

astrosat_users/serializers/serializers_auth.py, astrosat_users/views/views_auth.py
The new `registration_stage` field was misspelt in the swagger documentation.  
More importantly, the `registration_stage` serializer field in the `RegisterSerializer` didn't correctly validate against choices
(this was b/c the `RegistrationSerializer` is _not_ a `ModelSerializer` where field attributes are set automatically based on the corresponding model fields).
=> chore(backend): fixed a missed error in PR #105

astrosat_users/views/views_customers.py
Don't send an invitation notification if you are inviting yourself (ie: as part of self-signup) to a customer.
This PR closes #118
=> feat(backend): don't invite self

astrosat_users/adapters.py, astrosat_users/models/models_users.py
Remove the "to" address from the "cc" & "bcc" addresses in `adapter.send_mail` to prevent duplicate messages.  Also, removed the filter in `User.onboard` to remove the "to" address since it's done by default now.
This PR closes #114
=> feat(backend): prevent duplicate cc messages

astrosat_users/views/views_auth.py, example/Pipfile, example/Pipfile.lock, example/example/settings.py
This PR closes #121 
Since drf-yasg appears to be no longer maintained, I have no migrated to drf-yasg2 and updated any references to it.
I also had to pin factory-boy to version 3.0.1, since it introduced new `Locale` errors. I also had to unpin pytest, so it uses the latest version.
I did notice GitHub reporting a vulnerability: https://github.com/astrosat/django-astrosat-users/network/alert/example/Pipfile.lock/cryptography/open, we don't directly use this library, most likely a dependency of a dependency, but we might want to specify it directly, not sure and looking for advice.
=> Migrate to drf-yasg2

astrosat_users/adapters.py, astrosat_users/conf/settings.py, astrosat_users/models/models_customers.py, astrosat_users/templates/astrosat_users/email/invitation_message.txt, example/example/tests/test_customer_views.py
A new or existing user can be invited to join a customer.  If the user is new, they must reset their password.  The reset password link is therefore included in the invitation email.  If the user is existing, there was no link invcluded.
This PR adds a simple login link to the invitation email in the case of existing users.
This PR closes #123
=> 123 invitation link

astrosat_users/serializers/serializers_customers.py, example/example/tests/test_customer_views.py
Ensuring that a newly-created customer_user has accept_terms set to False.  This means they will be required to accept the terms upon logging in.
=> feat(backend): new customer-users must explicitly accept terms

astrosat_users/views/views_auth.py, example/example/tests/test_passwords.py
Upon a successful password reset the output of UserSerializerLite is included in the Response.
=> feat(backend): add user details to reset-password response

astrosat_users/views/views_customers.py, example/Pipfile.lock
Used new `swagger_fake` decorator for views that need it, instead of explicitly and repeatedly specifying the same checks for swagger schema generation in each of those views.
=> feat(backend): used swagger_fake decorator

astrosat_users/serializers/serializers_customers.py
The **orbis** client sometimes includes empty strings in form submissions.  These ought to be converted to `None` for some fields.
=> feat(backend): ignore blank CustomerSerializer fields

astrosat_users/urls.py, example/Pipfile.lock, example/example/tests/test_user_views.py
Use custom DRF Routers that can support requests with or without trailing slashes.
=> fix(backend): add slashless routers

astrosat_users/serializers/serializers_users.py, example/example/tests/test_user_serializers.py
This PR closes #969
I have added the Customer's name to the `UserSerializer`, this has been requested as part of the User Tracking in orbis.
=> Add Customer name to serializer

astrosat_users/adapters.py, astrosat_users/serializers/serializers_auth.py, example/Pipfile.lock, example/example/tests/test_registration.py
The "name" field passed to **django-astrosat-users** by **orbis** during registration is not being propagated to the `RegisterSerializer`.  
Technically, it _shouldn't_ be since registration is just about providing the username (which is the email address in this case) and password.  However, **orbis** decided to be different b/c... reasons.
This PR adds the "name" field to the `RegisterSerializer` and updated the `save_user` adapter method to pass that field to the registered `user`.
This PR closes #138
=> allow user name to be specified during registration

astrosat_users/apps.py, example/Pipfile.lock
Rather than update `default_auo_field` globally (as I did w/ #143), explicitly specify `default_auto_field` on the "astrosat_users" app.
This way I don't have to globally update `default_auto_field` to "django.db.models.BigAutoField" in projects and run the risk of creating custom migrations for other reusable apps that haven't yet upgraded to Django 3.2 (and therefore still use "django.db.models.AutoField").
=> chore(backend): update default_auto_field on a per-app basis

astrosat_users/serializers/serializers_users.py, astrosat_users/views/views_users.py
Added user to context of `UserSerializer` so that it is available to the corresponding `UserProfileSerializers`.  Just in case any of them need access to it for their own nested serializers.
This is a bit convoluted b/c of https://github.com/encode/django-rest-framework/issues/2555.
=> feat(backend): passed context to nested serializers

astrosat_users/views/views_users.py
Although I still pass the parent context from `UserSerializers` to `UserProfileSerializers`, I no longer explicitly add "user" to that context.  It is just too complicated to ensure the context is always correct since the `UserSerializer` is used in so many different ways.
Instead, I split the serializer in **orbis** that was giving me so much trouble into 2 distinct classes:
* the `OrbisUserFeedbackRecordSerializer` which is used by the `OrbisUserFeedbackRecordView` - _which has a `ContextVariableDefault` field because it's used outside the `OrbisUserProfileSerializer`_
* and the `OrbisUserFeedbackRecordNestedSerializer` which is used by every other
view and so is never used w/out a parent `OrbisUserProfileSerializer` - _and therefore has no need of a `ContextVariableDefault` field_
=> chore(backend): no longer adding "user" to context of UserViewSet

astrosat_users/checks.py
Allowed projects that use django-astrosat-users to use custom serializers/forms/etc. for authentication other than those defined in **django-astrosat-users** (as long as they use _something_).
=> Allow custom settings

astrosat_users/serializers/serializers_auth.py, astrosat_users/views/views_auth.py
When a user registers a customer and customer_user is now created.  When a user verifies their email address, that customer_user should now be activated.
=> feat(backend): activate customer-user on login

astrosat_users/adapters.py, astrosat_users/forms/forms_auth.py, astrosat_users/serializers/serializers_auth.py, example/Pipfile.lock, example/example/tests/test_registration.py
dj_rest_auth recently changed the way users are registered; They added additional checks to the process.  This means that the adapter code that creates a user doesn't actually always save that user anymore - saving is done in the serializer after the additional checks.  Therefore, the notification code was never running.  This commit moves the notification code into the serializer to be called after the new checks have passed. I added similar code in the form.
=> Move email notification from adapter to form/serializer

astrosat_users/checks.py, astrosat_users/conf/settings.py, example/Pipfile, example/Pipfile.lock, example/example/settings.py, example/example/tests/test_auth_api_errors.py, example/example/tests/test_login_logout.py, example/example/tests/test_passwords.py, setup.py
The current version of dj-rest-auth-social does not support the latest
version of django-allauth.  This should be fixed upstream shortly.  In
the meantime, b/c I'm not using social authentication I can just
uninstall dj-rest-auth social.  While still keeping
allauth.accounts.social so existing code works.
A few tests were tweaked b/c recent versions of  dj-rest-auth improved
security by not revealing that emails aren't sent when invalid emails
are used w/ the reset pasword views.
This PR closes #
=> chore(backend): removed dj-rest-auth-social
